server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/C:\myproject\MSA_Service_prac\config-git
        git:
          uri: file://C:\myproject\MSA_Service_prac\config-git #yml file directory that i designated location of git add
