server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:\Users\runnz\sample_repo
          ##file://${user:home}/C:\myproject\MSA_Service_prac\config-git:
        git:
          uri: file://C:\myproject\MSA_Service_prac\config-git #yml file directory that i designated location of git add

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
